-- Generated by the PSL visual editor
-- Run this in Supabase > SQL Editor.

-- Table: profiles
create table if not exists public."profiles" (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  "display_name" text,
  "avatar_url" text,
  "bio" text,
  "updated_at" timestamptz
);

alter table public."profiles" add column if not exists "display_name" text;
alter table public."profiles" alter column "display_name" type text using "display_name"::text;
alter table public."profiles" add column if not exists "avatar_url" text;
alter table public."profiles" alter column "avatar_url" type text using "avatar_url"::text;
alter table public."profiles" add column if not exists "bio" text;
alter table public."profiles" alter column "bio" type text using "bio"::text;
alter table public."profiles" add column if not exists "updated_at" timestamptz;
alter table public."profiles" alter column "updated_at" type timestamptz using "updated_at"::timestamptz;
alter table public."profiles" add column if not exists created_at timestamptz not null default now();
alter table public."profiles" add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public."profiles" enable row level security;
drop policy if exists "profiles_public_read" on public."profiles";
drop policy if exists "profiles_authenticated_read" on public."profiles";
drop policy if exists "profiles_own_select" on public."profiles";
drop policy if exists "profiles_own_insert" on public."profiles";
drop policy if exists "profiles_own_update" on public."profiles";
drop policy if exists "profiles_own_delete" on public."profiles";
revoke all on table public."profiles" from anon;
grant select, insert, update, delete on table public."profiles" to authenticated;
create policy "profiles_own_select" on public."profiles"
for select to authenticated using ((select auth.uid()) = user_id);
create policy "profiles_own_insert" on public."profiles"
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "profiles_own_update" on public."profiles"
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "profiles_own_delete" on public."profiles"
for delete to authenticated using ((select auth.uid()) = user_id);


create index if not exists "profiles_user_id_idx" on public."profiles" (user_id);
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'profiles_user_id_fkey') then
    alter table public."profiles"
      add constraint "profiles_user_id_fkey"
      foreign key ("user_id")
      references auth."users" ("id")
      on delete cascade;
  end if;
end $$;
create index if not exists "profiles_user_id_idx"
on public."profiles" ("user_id");

-- Table: user_roles
create table if not exists public."user_roles" (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  "user_id" uuid,
  "role" text
);

alter table public."user_roles" add column if not exists "user_id" uuid;
alter table public."user_roles" alter column "user_id" type uuid using "user_id"::uuid;
alter table public."user_roles" add column if not exists "role" text;
alter table public."user_roles" alter column "role" type text using "role"::text;
alter table public."user_roles" add column if not exists created_at timestamptz not null default now();

alter table public."user_roles" enable row level security;
drop policy if exists "user_roles_public_read" on public."user_roles";
drop policy if exists "user_roles_authenticated_read" on public."user_roles";
drop policy if exists "user_roles_own_select" on public."user_roles";
drop policy if exists "user_roles_own_insert" on public."user_roles";
drop policy if exists "user_roles_own_update" on public."user_roles";
drop policy if exists "user_roles_own_delete" on public."user_roles";
revoke all on table public."user_roles" from anon, authenticated;



do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'user_roles_user_id_fkey') then
    alter table public."user_roles"
      add constraint "user_roles_user_id_fkey"
      foreign key ("user_id")
      references auth."users" ("id")
      on delete cascade;
  end if;
end $$;
create index if not exists "user_roles_user_id_idx"
on public."user_roles" ("user_id");

-- Table: practices
create table if not exists public."practices" (
  id uuid primary key default gen_random_uuid(),
  published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  "created_by" uuid,
  "source" text,
  "title" text,
  "description" text,
  "media_url" text,
  "mediapipe_reference" jsonb,
  "difficulty" numeric,
  "estimated_minutes" numeric,
  "updated_at" timestamptz
);

alter table public."practices" add column if not exists "created_by" uuid;
alter table public."practices" alter column "created_by" type uuid using "created_by"::uuid;
alter table public."practices" add column if not exists "source" text;
alter table public."practices" alter column "source" type text using "source"::text;
alter table public."practices" add column if not exists "title" text;
alter table public."practices" alter column "title" type text using "title"::text;
alter table public."practices" add column if not exists "description" text;
alter table public."practices" alter column "description" type text using "description"::text;
alter table public."practices" add column if not exists "media_url" text;
alter table public."practices" alter column "media_url" type text using "media_url"::text;
alter table public."practices" add column if not exists "mediapipe_reference" jsonb;
alter table public."practices" alter column "mediapipe_reference" type jsonb using "mediapipe_reference"::jsonb;
alter table public."practices" add column if not exists "difficulty" numeric;
alter table public."practices" alter column "difficulty" type numeric using "difficulty"::numeric;
alter table public."practices" add column if not exists "estimated_minutes" numeric;
alter table public."practices" alter column "estimated_minutes" type numeric using "estimated_minutes"::numeric;
alter table public."practices" add column if not exists "updated_at" timestamptz;
alter table public."practices" alter column "updated_at" type timestamptz using "updated_at"::timestamptz;
alter table public."practices" add column if not exists created_at timestamptz not null default now();
alter table public."practices" add column if not exists published boolean not null default false;
alter table public."practices" add column if not exists sort_order integer not null default 0;

alter table public."practices" enable row level security;
drop policy if exists "practices_public_read" on public."practices";
drop policy if exists "practices_authenticated_read" on public."practices";
drop policy if exists "practices_own_select" on public."practices";
drop policy if exists "practices_own_insert" on public."practices";
drop policy if exists "practices_own_update" on public."practices";
drop policy if exists "practices_own_delete" on public."practices";
grant select on table public."practices" to anon, authenticated;
create policy "practices_public_read" on public."practices"
for select to anon, authenticated using (published = true);

create index if not exists "practices_published_sort_idx"
on public."practices" (published, sort_order);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'practices_created_by_fkey') then
    alter table public."practices"
      add constraint "practices_created_by_fkey"
      foreign key ("created_by")
      references auth."users" ("id")
      on delete set null;
  end if;
end $$;
create index if not exists "practices_created_by_idx"
on public."practices" ("created_by");

-- Table: practice_attempts
create table if not exists public."practice_attempts" (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  "practice_id" uuid,
  "score" numeric,
  "feedback" text,
  "mediapipe_result" jsonb,
  "duration_seconds" numeric
);

alter table public."practice_attempts" add column if not exists "practice_id" uuid;
alter table public."practice_attempts" alter column "practice_id" type uuid using "practice_id"::uuid;
alter table public."practice_attempts" add column if not exists "score" numeric;
alter table public."practice_attempts" alter column "score" type numeric using "score"::numeric;
alter table public."practice_attempts" add column if not exists "feedback" text;
alter table public."practice_attempts" alter column "feedback" type text using "feedback"::text;
alter table public."practice_attempts" add column if not exists "mediapipe_result" jsonb;
alter table public."practice_attempts" alter column "mediapipe_result" type jsonb using "mediapipe_result"::jsonb;
alter table public."practice_attempts" add column if not exists "duration_seconds" numeric;
alter table public."practice_attempts" alter column "duration_seconds" type numeric using "duration_seconds"::numeric;
alter table public."practice_attempts" add column if not exists created_at timestamptz not null default now();
alter table public."practice_attempts" add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public."practice_attempts" enable row level security;
drop policy if exists "practice_attempts_public_read" on public."practice_attempts";
drop policy if exists "practice_attempts_authenticated_read" on public."practice_attempts";
drop policy if exists "practice_attempts_own_select" on public."practice_attempts";
drop policy if exists "practice_attempts_own_insert" on public."practice_attempts";
drop policy if exists "practice_attempts_own_update" on public."practice_attempts";
drop policy if exists "practice_attempts_own_delete" on public."practice_attempts";
revoke all on table public."practice_attempts" from anon;
grant select, insert, update, delete on table public."practice_attempts" to authenticated;
create policy "practice_attempts_own_select" on public."practice_attempts"
for select to authenticated using ((select auth.uid()) = user_id);
create policy "practice_attempts_own_insert" on public."practice_attempts"
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "practice_attempts_own_update" on public."practice_attempts"
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "practice_attempts_own_delete" on public."practice_attempts"
for delete to authenticated using ((select auth.uid()) = user_id);


create index if not exists "practice_attempts_user_id_idx" on public."practice_attempts" (user_id);
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'practice_attempts_user_id_fkey') then
    alter table public."practice_attempts"
      add constraint "practice_attempts_user_id_fkey"
      foreign key ("user_id")
      references auth."users" ("id")
      on delete cascade;
  end if;
end $$;
create index if not exists "practice_attempts_user_id_idx"
on public."practice_attempts" ("user_id");
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'practice_attempts_practice_id_fkey') then
    alter table public."practice_attempts"
      add constraint "practice_attempts_practice_id_fkey"
      foreign key ("practice_id")
      references public."practices" ("id")
      on delete cascade;
  end if;
end $$;
create index if not exists "practice_attempts_practice_id_idx"
on public."practice_attempts" ("practice_id");

-- Table: practice_progress
create table if not exists public."practice_progress" (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  "practice_id" uuid,
  "status" text,
  "best_score" numeric,
  "attempts_count" numeric,
  "last_practiced_at" timestamptz
);

alter table public."practice_progress" add column if not exists "practice_id" uuid;
alter table public."practice_progress" alter column "practice_id" type uuid using "practice_id"::uuid;
alter table public."practice_progress" add column if not exists "status" text;
alter table public."practice_progress" alter column "status" type text using "status"::text;
alter table public."practice_progress" add column if not exists "best_score" numeric;
alter table public."practice_progress" alter column "best_score" type numeric using "best_score"::numeric;
alter table public."practice_progress" add column if not exists "attempts_count" numeric;
alter table public."practice_progress" alter column "attempts_count" type numeric using "attempts_count"::numeric;
alter table public."practice_progress" add column if not exists "last_practiced_at" timestamptz;
alter table public."practice_progress" alter column "last_practiced_at" type timestamptz using "last_practiced_at"::timestamptz;
alter table public."practice_progress" add column if not exists created_at timestamptz not null default now();
alter table public."practice_progress" add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public."practice_progress" enable row level security;
drop policy if exists "practice_progress_public_read" on public."practice_progress";
drop policy if exists "practice_progress_authenticated_read" on public."practice_progress";
drop policy if exists "practice_progress_own_select" on public."practice_progress";
drop policy if exists "practice_progress_own_insert" on public."practice_progress";
drop policy if exists "practice_progress_own_update" on public."practice_progress";
drop policy if exists "practice_progress_own_delete" on public."practice_progress";
revoke all on table public."practice_progress" from anon;
grant select, insert, update, delete on table public."practice_progress" to authenticated;
create policy "practice_progress_own_select" on public."practice_progress"
for select to authenticated using ((select auth.uid()) = user_id);
create policy "practice_progress_own_insert" on public."practice_progress"
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "practice_progress_own_update" on public."practice_progress"
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "practice_progress_own_delete" on public."practice_progress"
for delete to authenticated using ((select auth.uid()) = user_id);


create index if not exists "practice_progress_user_id_idx" on public."practice_progress" (user_id);
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'practice_progress_user_id_fkey') then
    alter table public."practice_progress"
      add constraint "practice_progress_user_id_fkey"
      foreign key ("user_id")
      references auth."users" ("id")
      on delete cascade;
  end if;
end $$;
create index if not exists "practice_progress_user_id_idx"
on public."practice_progress" ("user_id");
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'practice_progress_practice_id_fkey') then
    alter table public."practice_progress"
      add constraint "practice_progress_practice_id_fkey"
      foreign key ("practice_id")
      references public."practices" ("id")
      on delete cascade;
  end if;
end $$;
create index if not exists "practice_progress_practice_id_idx"
on public."practice_progress" ("practice_id");

-- Table: favorite_practices
create table if not exists public."favorite_practices" (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  "practice_id" uuid
);

alter table public."favorite_practices" add column if not exists "practice_id" uuid;
alter table public."favorite_practices" alter column "practice_id" type uuid using "practice_id"::uuid;
alter table public."favorite_practices" add column if not exists created_at timestamptz not null default now();
alter table public."favorite_practices" add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public."favorite_practices" enable row level security;
drop policy if exists "favorite_practices_public_read" on public."favorite_practices";
drop policy if exists "favorite_practices_authenticated_read" on public."favorite_practices";
drop policy if exists "favorite_practices_own_select" on public."favorite_practices";
drop policy if exists "favorite_practices_own_insert" on public."favorite_practices";
drop policy if exists "favorite_practices_own_update" on public."favorite_practices";
drop policy if exists "favorite_practices_own_delete" on public."favorite_practices";
revoke all on table public."favorite_practices" from anon;
grant select, insert, update, delete on table public."favorite_practices" to authenticated;
create policy "favorite_practices_own_select" on public."favorite_practices"
for select to authenticated using ((select auth.uid()) = user_id);
create policy "favorite_practices_own_insert" on public."favorite_practices"
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "favorite_practices_own_update" on public."favorite_practices"
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "favorite_practices_own_delete" on public."favorite_practices"
for delete to authenticated using ((select auth.uid()) = user_id);


create index if not exists "favorite_practices_user_id_idx" on public."favorite_practices" (user_id);
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'favorite_practices_user_id_fkey') then
    alter table public."favorite_practices"
      add constraint "favorite_practices_user_id_fkey"
      foreign key ("user_id")
      references auth."users" ("id")
      on delete cascade;
  end if;
end $$;
create index if not exists "favorite_practices_user_id_idx"
on public."favorite_practices" ("user_id");
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'favorite_practices_practice_id_fkey') then
    alter table public."favorite_practices"
      add constraint "favorite_practices_practice_id_fkey"
      foreign key ("practice_id")
      references public."practices" ("id")
      on delete cascade;
  end if;
end $$;
create index if not exists "favorite_practices_practice_id_idx"
on public."favorite_practices" ("practice_id");